app/routes/affairs.py
from dataclasses import asdict
from datetime import datetime, timedelta
from http import client

from dacite import from_dict
from flask import Blueprint, abort, redirect, render_template, request, url_for

from app.crud.affair import (
    add_person,
    add_resource,
    del_person_from_affair,
    del_resource_from_affair,
    delete_affair,
    get_affair,
    get_affairs,
    get_people_links_for_affair,
    get_resource_links_for_affair,
    insert_affair,
    mark_affair_done,
    update_affair,
)
from app.crud.category import get_categories
from app.crud.exceptions import AffairNotFound, PersonNotFound, ResourceNotFound
from app.crud.person import get_person
from app.crud.resource import get_resource
from app.forms.add_person_to_affair import PersonAffairForm
from app.forms.add_resource_to_affair import ResourceAffairForm
from app.forms.affair import AffairForm
from app.models.affair import AffairInput, AffairPeriod, AffairPriority

affairs_bp = Blueprint("affairs", __name__)


@affairs_bp.route("/")
def affairs():
    args = request.args
    from_date = args.get("from_date_time", "")
    to_date = args.get("to_date_time", "")
    is_open = args.get("is_open")
    from_date = (
        datetime.strptime(from_date, "%Y-%m-%dT%H:%M")
        if from_date != ""
        else datetime(1900, 1, 1)
    )
    to_date = (
        datetime.strptime(to_date, "%Y-%m-%dT%H:%M")
        if to_date != ""
        else datetime(2100, 1, 1)
    )
    return render_template(
        "affairs.html.j2",
        affairs=get_affairs(from_date, to_date, is_open),
        from_date_time=args.get("from_date_time", ""),
        to_date_time=args.get("to_date_time", ""),
        is_open=args.get("is_open"),
    )


@affairs_bp.route("/<int:affair_id>")
def affair(affair_id):
    try:
        affair = get_affair(affair_id)
    except AffairNotFound:
        abort(client.NOT_FOUND)
    return render_template(
        "affair.html.j2",
        affair=affair,
        id=affair_id,
        affair_period_enum=AffairPeriod,
        affair_priority_enum=AffairPriority,
    )


@affairs_bp.route("/<int:affair_id>/mark_done")
def affair_done(affair_id):
    try:
        affair = get_affair(affair_id)
    except AffairNotFound:
        abort(client.NOT_FOUND)
    if affair.done_percent != 100:
        if affair.period and affair.linked_time:
            affair.linked_time += timedelta(seconds=affair.period)
            affair.done_percent = 0
            while affair.linked_time < datetime.now():
                affair.linked_time += timedelta(seconds=affair.period)
            new_affair_id = insert_affair(
                from_dict(data_class=AffairInput, data=asdict(affair))
            )
            for resource in affair.resources:
                add_resource(new_affair_id, resource.id, resource.quantity)
            for person in affair.people:
                add_person(new_affair_id, person.id)
        mark_affair_done(affair_id)
    return redirect(url_for(".affairs"))


@affairs_bp.route("/<int:affair_id>/add_person", methods=("GET", "POST"))
def add_person_to_affair(affair_id):
    try:
        get_affair(affair_id)
    except AffairNotFound:
        abort(client.NOT_FOUND)
    form = PersonAffairForm()
    form.person_id.choices = [
        (person.id, " ".join(filter(None, (person.first_name, person.last_name))))
        for person in get_people_links_for_affair(affair_id)
    ]
    if form.validate_on_submit():
        person_id = form.person_id.data
        add_person(affair_id, person_id)
        return redirect(url_for(".affair", affair_id=affair_id))
    return render_template("add_person_to_affair.html.j2", form=form)


@affairs_bp.route(
    "/<int:affair_id>/delete_person/<int:person_id>", methods=("GET", "POST")
)
def delete_person_from_affair(affair_id, person_id):
    if request.method == "GET":
        try:
            affair = get_affair(affair_id)
            person = get_person(person_id)
        except (AffairNotFound, PersonNotFound):
            abort(client.NOT_FOUND)
        return render_template(
            "delete_person_from_affair.html.j2",
            affair=affair,
            person=person,
            affair_id=affair_id,
        )
    else:
        del_person_from_affair(affair_id, person_id)
    return redirect(url_for(".affair", affair_id=affair_id))


@affairs_bp.route("/<int:affair_id>/delete", methods=("GET", "POST"))
def del_affair(affair_id):
    if request.method == "GET":
        try:
            affair = get_affair(affair_id)
        except AffairNotFound:
            abort(client.NOT_FOUND)
        return render_template(
            "delete_affair.html.j2", affair=affair, affair_id=affair_id
        )
    else:
        delete_affair(affair_id)
        return redirect(url_for(".affairs"))


@affairs_bp.route("/<int:affair_id>/add_resource", methods=("GET", "POST"))
def add_resource_to_affair(affair_id):
    try:
        get_affair(affair_id)
    except AffairNotFound:
        abort(client.NOT_FOUND)
    form = ResourceAffairForm()
    form.resource_id.choices = [
        (resource.id, resource.name)
        for resource in get_resource_links_for_affair(affair_id)
    ]
    if form.validate_on_submit():
        resource_id = form.resource_id.data
        quantity = form.quantity.data
        add_resource(affair_id, resource_id, quantity)
        return redirect(url_for(".affair", affair_id=affair_id))
    return render_template("add_resource_to_affair.html.j2", form=form)


@affairs_bp.route(
    "/<int:affair_id>/delete_resource/<int:resource_id>", methods=("GET", "POST")
)
def delete_resource_from_affair(affair_id, resource_id):
    if request.method == "GET":
        try:
            affair = get_affair(affair_id)
            resource = get_resource(resource_id)
        except (AffairNotFound, ResourceNotFound):
            abort(client.NOT_FOUND)
        return render_template(
            "delete_resource_from_affair.html.j2",
            affair=affair,
            resource=resource,
            affair_id=affair_id,
        )
    else:
        del_resource_from_affair(affair_id, resource_id)
    return redirect(url_for(".affair", affair_id=affair_id))


@affairs_bp.route("/new", methods=("GET", "POST"))
def new_affair():
    form = AffairForm()
    form.category_id.choices = [
        (category.id, category.name) for category in get_categories()
    ]
    form.category_id.choices.append((-1, "Без Категории"))
    if form.validate_on_submit():
        f = dict(**form.data)
        f["period"] = None if f["period"] == 0 else f["period"]
        f["category_id"] = None if f["category_id"] == -1 else f["category_id"]
        affair_id = insert_affair(from_dict(data_class=AffairInput, data=f))
        return redirect(url_for(".affair", affair_id=affair_id))
    return render_template("new_affair.html.j2", form=form)


@affairs_bp.route("/<int:affair_id>/edit", methods=("GET", "POST"))
def edit_affair(affair_id):
    try:
        affair = get_affair(affair_id)
    except AffairNotFound:
        abort(client.NOT_FOUND)
    form = AffairForm(obj=affair)
    form.category_id.choices = [
        (category.id, category.name) for category in get_categories()
    ]
    form.category_id.choices.append((-1, "Без Категории"))
    if form.validate_on_submit():
        f = dict(**form.data)
        f["period"] = None if f["period"] == 0 else f["period"]
        f["category_id"] = None if f["category_id"] == -1 else f["category_id"]
        update_affair(from_dict(data_class=AffairInput, data=f), affair_id)
        return redirect(url_for(".affair", affair_id=affair_id))
    return render_template("edit_affair.html.j2", form=form)


@affairs_bp.route("/<int:affair_id>/new_sub_affair", methods=("GET", "POST"))
def new_sub_affair(affair_id):
    try:
        get_affair(affair_id)
    except AffairNotFound:
        abort(client.NOT_FOUND)
    form = AffairForm()
    form.category_id.choices = [
        (category.id, category.name) for category in get_categories()
    ]
    form.category_id.choices.append((-1, "Без Категории"))
    if form.validate_on_submit():
        f = dict(**form.data)
        f["period"] = None if f["period"] == 0 else f["period"]
        f["category_id"] = None if f["category_id"] == -1 else f["category_id"]
        affair_id = insert_affair(
            from_dict(data_class=AffairInput, data=f), parent_affair_id=affair_id
        )
        return redirect(url_for(".affair", affair_id=affair_id))
    return render_template("new_affair.html.j2", form=form)

app/routes/categories.py
from http import client

from dacite import from_dict
from flask import Blueprint, abort, redirect, render_template, request, url_for

from app.crud.category import (
    delete_category,
    get_categories,
    get_category,
    insert_category,
    update_category,
)
from app.crud.exceptions import CategoryNotFound
from app.forms.category import CategoryForm
from app.models.category import Category

categories_bp = Blueprint("categories", __name__)


@categories_bp.route("/new", methods=("GET", "POST"))
def new_category():
    form = CategoryForm()
    if form.validate_on_submit():
        insert_category(form.name.data)
        return redirect(url_for("categories.categories"))
    return render_template("new_category.html.j2", form=form)


@categories_bp.route("/")
def categories():
    return render_template("categories.html.j2", categories=get_categories())


@categories_bp.route("/<int:category_id>/delete", methods=("GET", "POST"))
def del_category(category_id):
    if request.method == "GET":
        try:
            category = get_category(category_id)
        except CategoryNotFound:
            abort(client.NOT_FOUND)
        return render_template("delete_category.html.j2", category=category)
    else:
        delete_category(category_id)
        return redirect(url_for(".categories"))


@categories_bp.route("/<int:category_id>/edit", methods=("GET", "POST"))
def edit_category(category_id):
    try:
        category = get_category(category_id)
    except CategoryNotFound:
        abort(client.NOT_FOUND)
    form = CategoryForm(obj=category)
    if form.validate_on_submit():
        update_category(from_dict(data_class=Category, data=form.data), category_id)
        return redirect(url_for(".categories"))
    return render_template("edit_category.html.j2", form=form)

app/routes/people.py
from http import client
from dacite import from_dict
from flask import Blueprint, abort, redirect, render_template, request, url_for
from app.crud.exceptions import PersonNotFound

from app.crud.person import (
    delete_person,
    get_people_links,
    get_person,
    insert_person,
    update_person,
)
from app.forms.person import PersonForm
from app.models.person import Person


people_bp = Blueprint("people", __name__)


@people_bp.route("/")
def people():
    return render_template("people.html.j2", people=get_people_links())


@people_bp.route("/new", methods=("GET", "POST"))
def new_person():
    form = PersonForm()
    if form.validate_on_submit():
        person_id = insert_person(from_dict(data_class=Person, data=form.data))
        return redirect(url_for(".person", person_id=person_id))
    return render_template("new_person.html.j2", form=form)


@people_bp.route("/<int:person_id>")
def person(person_id):
    try:
        person = get_person(person_id)
    except PersonNotFound:
        abort(client.NOT_FOUND)
    return render_template("person.html.j2", person=person, person_id=person_id)


@people_bp.route("/<int:person_id>/delete", methods=("GET", "POST"))
def del_person(person_id):
    if request.method == "GET":
        try:
            person = get_person(person_id)
        except PersonNotFound:
            abort(client.NOT_FOUND)
        return render_template(
            "delete_person.html.j2", person=person, person_id=person_id
        )
    else:
        delete_person(person_id)
        return redirect(url_for(".people"))


@people_bp.route("/<int:person_id>/edit", methods=("GET", "POST"))
def edit_person(person_id):
    try:
        person = get_person(person_id)
    except PersonNotFound:
        abort(client.NOT_FOUND)
    form = PersonForm(obj=person)
    if form.validate_on_submit():
        update_person(from_dict(data_class=Person, data=form.data), person_id)
        return redirect(url_for(".person", person_id=person_id))
    return render_template("edit_person.html.j2", form=form)

app/routes/reources.py
from http import client
from dacite import from_dict
from flask import Blueprint, abort, redirect, render_template, request, url_for
from app.crud.exceptions import ResourceNotFound

from app.crud.resource import (
    delete_resource,
    get_resource,
    get_resources_links,
    insert_resource,
    update_resource,
)
from app.forms.resource import ResourceForm
from app.models.resource import Resource


resources_bp = Blueprint("resources", __name__)


@resources_bp.route("/")
def resources():
    return render_template("resources.html.j2", resources=get_resources_links())


@resources_bp.route("/<int:resource_id>")
def resource(resource_id):
    try:
        resource = get_resource(resource_id)
    except ResourceNotFound:
        abort(client.NOT_FOUND)
    return render_template(
        "resource.html.j2", resource=resource, resource_id=resource_id
    )


@resources_bp.route("/new", methods=("GET", "POST"))
def new_resource():
    form = ResourceForm()
    if form.validate_on_submit():
        resource_id = insert_resource(from_dict(data_class=Resource, data=form.data))
        return redirect(url_for(".resource", resource_id=resource_id))
    return render_template("new_resource.html.j2", form=form)


@resources_bp.route("/<int:resource_id>/delete", methods=("GET", "POST"))
def del_resource(resource_id):
    if request.method == "GET":
        try:
            resource = get_resource(resource_id)
        except ResourceNotFound:
            abort(client.NOT_FOUND)
        return render_template(
            "delete_resource.html.j2", resource=resource, resource_id=resource_id
        )
    else:
        delete_resource(resource_id)
        return redirect(url_for(".resources"))


@resources_bp.route("/<int:resource_id>/edit", methods=("GET", "POST"))
def edit_resource(resource_id):
    try:
        resource = get_resource(resource_id)
    except ResourceNotFound:
        abort(client.NOT_FOUND)
    form = ResourceForm(obj=resource)
    if form.validate_on_submit():
        update_resource(from_dict(data_class=Resource, data=form.data), resource_id)
        return redirect(url_for(".resource", resource_id=resource_id))
    return render_template("edit_resource.html.j2", form=form)

app/templates/404.html.j2
{% extends "layout.html.j2" %}
{% block title %}Страница не найдена{% endblock %}
{% block content %}

<div class="grid-x grid-padding-x">
  <div class="medium-12 cell">
    <p>Вы выполнили запрос к несуществующей странице</p>
    <p>Адрес запроса: {{ url }}</p>
    <p>Вернуться к <a href="/">основному содержимому</a></p>
  </div>
</div>

{% endblock %}

app/templates/add_person_to_affair.html.j2
{% import 'forms.j2' as forms %}
{% extends 'layout.html.j2' %}
{% block title %}Добавить человека к делу{% endblock %}
{% block content %}
<h1>Добавить человека к делу</h1>
<form action="" method="post" novalidate>
  {{ form.hidden_tag() }}
  <p>
    {{ form.person_id.label }}
    {{ forms.with_errors(form.person_id) }}
  </p>
  <p>{{ form.submit() }}</p>
</form>
{% endblock %}

app/templates/affair.html.j2
{% extends 'layout.html.j2' %}
{% block title %}Дело {{ affair.title }}{% endblock %}
{% block content %}
<h2>{{ affair.title }}</h2>
<div class="grid-x grid-padding-x">
    <table>
        <tr>
            <th>Название</th>
            <td>{{ affair.title }}</td>
        </tr>
        {% if affair.description %}
        <tr>
            <th>Описание</th>
            <td>{{ affair.description }}</td>
        </tr>
        {% endif %}
        {% if affair.linked_time %}
        <tr>
            <th>Привязка ко времени</th>
            <td>{{ affair.linked_time.strftime("%d.%m.%Y в %H:%M") }}</td>
        </tr>
        {% endif %}
        {% if affair.period %}
        <tr>
            <th>Период</th>
            <td>{{ affair_period_enum(affair.period).label }}</td>
        </tr>
        {% endif %}
        <tr>
            <th>Приоритет</th>
            <td>{{ affair_priority_enum[affair.priority].value }}</td>
        </tr>
        <tr>
            <th>Прогресс выполнения</th>
            <td>{{ affair.done_percent }}%</td>
        </tr>
        <tr>
            <th>Категория</th>
            <td>{{ affair.category if affair.category else "Не установлена" }}</td>
        </tr>
        {% if affair.parent_affair_id %}
        <tr>
            <th>Родительское дело</th>
            <td><a href="{{ url_for('affairs.affair', affair_id=affair.parent_affair_id) }}">{{
                    affair.parent_affair_title }}</a></td>
        </tr>
        {% endif %}
        <tr>
            <th>Круг вовлеченных лиц</th>
            <td>
                <ul>
                    {% for person in affair.people %}
                    <li>
                        <a href="{{ url_for('people.person', person_id=person.id) }}">
                            {{ person.first_name }} {{ person.last_name if
                            person.last_name}}
                        </a>
                        <a href="{{ url_for('affairs.delete_person_from_affair', affair_id=id, person_id=person.id) }}">(удалить)</a>
                    </li>
                    {% endfor %}
                </ul>
                <a href="{{ url_for('affairs.add_person_to_affair', affair_id=id) }}">Добавить вовлеченное лицо</a>
            </td>
        </tr>
        <tr>
            <th>Используемые ресурсы</th>
            <td>
                <ul>
                    {% for resource in affair.resources %}
                    <li><a href="{{ url_for('resources.resource', resource_id=resource.id) }}">
                            {{ resource.name }} {{ resource.quantity }} шт.    
                        </a>
                        <a href="{{ url_for('affairs.delete_resource_from_affair', affair_id=id, resource_id=resource.id) }}">(удалить)</a>
                    </li>
                    {% endfor %}
                </ul>
                <a href="{{ url_for('affairs.add_resource_to_affair', affair_id=id) }}">Добавить ресурс</a>
            </td>
        </tr>
    </table>
    <a class="button" href="{{ url_for('affairs.edit_affair', affair_id=id) }}">Редактировать</a>
    <a class="button alert" href="{{  url_for('affairs.del_affair', affair_id=id) }}">Удалить</a>
</div>
{% endblock %}

app/templates/affairs.html.j2
{% extends 'layout.html.j2' %}
{% block title %}Список дел{% endblock %}
{% block content %}
<h1>Список дел</h1>
<form method="GET">
    <div class="grid-x grid-padding-x align-bottom">
        <div class="medium-4 cell">
            Временной период
            <label>От:
                <input type="datetime-local" name="from_date_time" value="{{ from_date_time }}">
            </label>
        </div>
        <div class="medium-4 cell">
            <label>До:
                <input type="datetime-local" name="to_date_time" value="{{ to_date_time }}">
            </label>
        </div>
        <div class="medium-4 cell">
            <label>Незавершен
                <input type="radio" name="is_open" value="true" {% if is_open=="true" %}checked{% endif %}>
            </label>
            <label>Завершен
                <input type="radio" name="is_open" value="false" {% if is_open=="false" %}checked{% endif %}>
            </label>
        </div>
        <div class="medium-4 cell">
            <input type="submit" value="Фильтровать" class="button">
            <a href="/affairs" class="button">Сбросить</a>
        </div>
    </div>
</form>

<div class="grid-x grid-padding-x">
    <div class="medium-4 cell">
        <a href="{{ url_for('affairs.new_affair') }}" class="button">Добавить дело</a>
    </div>
    {% for affair in affairs %}
    <div class="medium-12 cell">
        <div class="callout">
            <p>
                <a href="{{ url_for('affairs.affair', affair_id=affair.id) }}"><b>{{ affair.title }}</b> 
                {{ affair.linked_time.strftime("%d.%m.%Y в %H:%M") if affair.linked_time }}</a>
            </p>
            <p>Степень завершенности {{ affair.done_percent }}%</p>
            {% if affair.done_percent != 100 %}
            <p>
                <a class="button tiny" href="{{ url_for('affairs.affair_done', affair_id=affair.id) }}">Пометить
                    выполненной</a>
                <a class="button tiny" href="{{ url_for('affairs.new_sub_affair', affair_id=affair.id) }}">Создать
                    связанное дело</a>
            </p>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/delete_affair.html.j2
{% extends "layout.html.j2" %}

{% block content %}

<div class="grid-x grid-padding-x">
  <div class="medium-12 cell">
    <p>Вы действительно хотите удалить дело {{ affair.name }}</p>
    <form method="post">
      <input type="submit" value="Да" class="button">
      <a class="button" href="{{ url_for('affairs.affair', affair_id=affair_id) }}">Нет, назад</a>
    </form>
  </div>
</div>

{% endblock %}

app/templates/delete_category.html.j2
{% extends "layout.html.j2" %}

{% block content %}

<div class="grid-x grid-padding-x">
  <div class="medium-12 cell">
    <p>Вы действительно хотите удалить категоирю {{ category.name }}</p>
    <form method="post">
      <input type="submit" value="Да" class="button">
      <a class="button" href="{{ url_for('categories.categories') }}">Нет, назад</a>
    </form>
  </div>
</div>

{% endblock %}

app/templates/edit_affair.html.j2
{% import 'forms.j2' as forms %}
{% extends 'layout.html.j2' %}
{% block title %}Редактировать дело{% endblock %}
{% block content %}
<h1>Редактировать дело</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.title.label }}
            {{ forms.with_errors(form.title, size=50) }}
        </p>
        <p>
            {{ form.description.label }}
            {{ forms.with_errors(form.description) }}
        </p>
        <p>
            {{ form.linked_time.label }}
            {{ forms.with_errors(form.linked_time) }}
        </p>
        <p>
            {{ form.period.label }}
            {{ forms.with_errors(form.period) }}
        </p>
        <p>
            {{ form.done_percent.label }}
            {{ forms.with_errors(form.done_percent, min=0, max=100) }}
        </p>
        <p>
            {{ form.priority.label }}
            {{ forms.with_errors(form.priority) }}
        </p>
        <p>
            {{ form.category_id.label }} <a href="{{ url_for('categories.new_category') }}" class="button small">Добавить категорию</a>
            {{ forms.with_errors(form.category_id) }}
        </p>
        <p><input class="button success" type="submit" value="Редактировать"></p>
    </form>
{% endblock %}

app/templates/edit_category.html.j2
{% import 'forms.j2' as forms %}
{% extends 'layout.html.j2' %}
{% block title %}Редактировать категорию{% endblock %}
{% block content %}
<h1>Редактировать категорию</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.name.label }}
            {{ forms.with_errors(form.name, size=50) }}
        </p>
        <p><input class="button success" type="submit" value="Редактировать"></p>
    </form>
{% endblock %}

app/templates/edit_person.html.j2
{% import 'forms.j2' as forms %}
{% extends 'layout.html.j2' %}
{% block title %}Редактировать человека{% endblock %}
{% block content %}
<h1>Редактировать человека</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.first_name.label }}
            {{ forms.with_errors(form.first_name, size=50) }}
        </p>
        <p>
            {{ form.last_name.label }}
            {{ forms.with_errors(form.last_name, size=50) }}
        </p>
        <p>
            {{ form.description.label }}
            {{ forms.with_errors(form.description, size=500) }}
        </p>
        <p>
            {{ form.contacts.label }}
            {{ forms.with_errors(form.contacts, size=100) }}
        </p>
        <p><input class="button success" type="submit" value="Редактировать"></p>
    </form>
{% endblock %}

app/templates/layout.html.j2
<!doctype html>
<html class="no-js" lang="ru-RU" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Нет заголовка{% endblock %}</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/foundation.css') }}">
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
</head>

<body>
  <div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Органайзер</li>
        <li><a href="/">Главная</a>
        <li><a href="{{ url_for('affairs.affairs') }}">Список дел</a></li>
        <li><a href="{{ url_for('people.people') }}">Список людей</a></li>
        <li><a href="{{ url_for('resources.resources') }}">Список ресурсов</a></li>
        <li><a href="{{ url_for('categories.categories') }}">Список категорий</a></li>
      </ul>
    </div>
  </div>
  <div class="grid-container">

    {% block content %}
    Нет содержимого
    {% endblock %}

  </div>
  <script src="{{ url_for('static', filename='js/vendor/jquery.js') }}"></script>
  <script src="{{ url_for('static', filename='js/vendor/what-input.js') }}"></script>
  <script src="{{ url_for('static', filename='js/vendor/foundation.js') }}"></script>
  <script src="{{ url_for('static', filename='js/app.js') }}"></script>
</body>

</html>

app/templates/new_affair.html.j2
{% import 'forms.j2' as forms %}
{% extends 'layout.html.j2' %}
{% block title %}Новое дело{% endblock %}
{% block content %}
<h1>Новое дело</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.title.label }}
            {{ forms.with_errors(form.title, size=50) }}
        </p>
        <p>
            {{ form.description.label }}
            {{ forms.with_errors(form.description) }}
        </p>
        <p>
            {{ form.linked_time.label }}
            {{ forms.with_errors(form.linked_time) }}
        </p>
        <p>
            {{ form.period.label }}
            {{ forms.with_errors(form.period) }}
        </p>
        <p>
            {{ form.done_percent.label }}
            {{ forms.with_errors(form.done_percent, min=0, max=100) }}
        </p>
        <p>
            {{ form.priority.label }}
            {{ forms.with_errors(form.priority) }}
        </p>
        <p>
            {{ form.category_id.label }} <a href="{{ url_for('categories.new_category') }}" class="button small">Добавить категорию</a>
            {{ forms.with_errors(form.category_id) }}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/new_category.html.j2
{% import 'forms.j2' as forms %}
{% extends 'layout.html.j2' %}
{% block title %}Новая категория{% endblock %}
{% block content %}
<h1>Новая категория</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.name.label }}
            {{ forms.with_errors(form.name, size=50) }}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/new_person.html.j2
{% import 'forms.j2' as forms %}
{% extends 'layout.html.j2' %}
{% block title %}Новый человек{% endblock %}
{% block content %}
<h1>Новый человек</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.first_name.label }}
            {{ forms.with_errors(form.first_name, size=50) }}
        </p>
        <p>
            {{ form.last_name.label }}
            {{ forms.with_errors(form.last_name, size=50) }}
        </p>
        <p>
            {{ form.description.label }}
            {{ forms.with_errors(form.description, size=500) }}
        </p>
        <p>
            {{ form.contacts.label }}
            {{ forms.with_errors(form.contacts, size=100) }}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/resource.html.j2
{% extends 'layout.html.j2' %}
{% block title %}{{ resource.name }}{% endblock %}
{% block content %}
<h2>Ресурс</h2>
<div class="grid-x grid-padding-x">
    <table>
        <tr>
            <th>Название</th>
            <td>{{ resource.name }}</td>
        </tr>
    </table>
    <a class="button" href="{{ url_for('resources.edit_resource', resource_id=resource_id) }}">Редактировать</a>
    <a class="button alert" href="{{ url_for('resources.del_resource', resource_id=resource_id) }}">Удалить</a>
</div>
{% endblock %}